import Head from 'next/head';
import React from 'react'
import { useState } from 'react';
import { getImageRandom, timer, isAnswer } from '@/functions/game';

const image = getImageRandom()

export default function Easy() {
    const [gameStarted, updateGameStarted] = useState(false)

    const [timeLeft, noTimeLeft] = useState(true)
    
    const [guessedAnswer, setAnswer] = useState(String)

    const [rightAnswer, checkAnswer] = useState(false)

    const src = '/magasins/' + image + '.png'
    const srcHalfBlurred = '/magasinsHalfBlurred/' + image + '.png'

    const answer = '/answers/' + image + '.txt'

    return (
        <><Head>
            <title>Bon courage</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            {gameStarted ? (
                <>
                    {timeLeft ? (<>
                        <h1 id='safeTimerDisplay'></h1>
                        <img src={srcHalfBlurred} id='imageHalfBlurred'></img>
                        <form>
                            <input type='text' id='textAnswer' onChange={(e) => {setAnswer(e.target.value)}}/>
                        </form>
                        
                        <button id='submitAnswer' onClick={() => isAnswer(guessedAnswer, noTimeLeft, checkAnswer, answer)}>envoyer</button>

                        </>) : (<>

                        <h1> TEMPS ÉCOULÉ !</h1>
                        <img src={src} id='image'></img>
                        <div>{guessedAnswer}</div>

                        </>)}
                </>
                    ) : (
                    <>
                        <button id='gameStart' onClick={timer(updateGameStarted, noTimeLeft)} >launch the game</button>
                    </>
                    )}
                </>)     
}