import Head from 'next/head';
import React, { useState } from 'react'

function timer() {
    if (typeof document !== 'undefined') {
        document.getElementById("gameStart").addEventListener("click", function () {
            var sec = 30
            var timer = setInterval(function () {
                if (typeof document !== 'undefined') {
                    document.getElementById('safeTimerDisplay').innerHTML = sec;
                    sec--;
                    if (sec < 0) {
                        clearInterval(timer)
                    }
                }
            }, 1000)
        })
    }

}

function getImageRandom() {
    return Math.floor(Math.random() * 8) + '.png'
}


export default function Home() {
    var image = getImageRandom()
    var src = '/magasinsHalfBlurred/' + image
    return (
        <><Head>
            <title>Bon courage</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <div id='safeTimerDisplay'></div>
            <button id='gameStart' onClick={timer()}>launch timer</button>
            <img src={src} id='imageHalfBlurred' ></img>

            <form>
                <input type='text'></input>
            </form></>
    )
}