import counter from '@/components/game';
import Head from 'next/head'
import { useEffect } from 'react';

function timer() {
    var sec = 30
    var timer = setInterval(function () {
        if (typeof document !== 'undefined') {
            document.getElementById('safeTimerDisplay').innerHTML = sec;
            sec--;
            if (sec < 0) {
                clearInterval(timer)
            }
        }
    }, 1000)
}

export default function Home() {
    var image = counter()
    console.log(image)
    return (
        <><Head>
            <title>Bon courage</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <div id='safeTimerDisplay'/>
            <form>
                <input type='text'></input>
            </form>
            <script>
                document.getElementById(safeTimerDisplay).onload = function() {timer()};
            </script></>
    )
}